#!/bin/sh

# exit if we are running chroot
if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then exit 0; fi

#
# System update hook
# Call system update script here
#
if [ -x /usr/local/bin/fenix-updater ]; then
	/usr/local/bin/fenix-updater
fi


exit 0
